name:                extensible-effects-th
version:             0.1.0.0
github:              "ivanovs-4/extensible-effects-th"
license:             BSD3
author:              "Sergey Ivanov"
maintainer:          "ivanovs-4@yandex.ru"
copyright:           "2018 Sergey Ivanov"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Helper to generate dsl operations for Control.Eff.Operational
category:            Control, Effect

description:         Please see the README on GitHub at <https://github.com/ivanovs-4/extensible-effects-th#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - template-haskell

executables:
  ee-simple:
    main:                Simple.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - extensible-effects
    - extensible-effects-th
    when:
      - condition: flag(examples)
        then:
          buildable: true
        else:
          buildable: false

flags:
  examples:
    description:       Build examples
    manual:            true
    default:           false

