name:                extensible-effects-th
version:             0.1.0.0
github:              "ivanovs-4/extensible-effects-th"
license:             BSD3
author:              "Sergey Ivanov"
maintainer:          "ivanovs-4@yandex.ru"
copyright:           "2018 Sergey Ivanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Control, Effect

description:         Please see the README on GitHub at <https://github.com/ivanovs-4/extensible-effects-th#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell

library:
  source-dirs: src

tests:
  extensible-effects-th-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - extensible-effects-th
